name: practice github actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .Net Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run : dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release
      
      - name: Publish
        run: dotnet publish -c Release -o dotnetcorewebapp .\

      - name: Deploy to IIS
        run: |
          iisreset /stop
          Copy-item dotnetcorewebapp/* c:/inetpub/wwwroot/dotnetcore-webapp -Recurse -Force
          iisreset /start

      - name: Curl the web to do smoke test
        run: curl http://localhost/dotnetcore-webapp
