name: practice github actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release
      - name: Publish
        run: dotnet publish -c Release -o dotnetcorewebapp .\
      - name: Stop IIS
        run: runas /user:jawad.h /savecred "net stop w3svc"
        shell: cmd
      - name: Deploy to IIS
        run: |
          $sourcePath = 'C:\actions-runner\testing\EmailServiceMinimalAPI\EmailServiceMinimalAPI\dotnetcorewebapp\*'
          $destinationPath = 'C:\inetpub\wwwroot\iistest'
          Get-ChildItem -Path $sourcePath -Recurse | Copy-Item -Destination $destinationPath -Recurse -Force
        shell: pwsh
      - name: List files in IIS
        run: Get-ChildItem -Path C:\inetpub\wwwroot\iistest -Recurse
        shell: pwsh
      - name: Start IIS
        run: net start w3svc
        shell: pwsh